version: '3.8'

services:
  invoice-llm:
    container_name: invoice-llm
    build: .
    ports:
      - "9090:8000"
    volumes:
      - ./input_pdfs:/app/input_pdfs
      - ./output_json:/app/output_json
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    stdin_open: true
